[package]
name = "capeos"
version = "0.1.0"
edition = "2024"


# used for cargo build
[profile.dev]
panic = "abort"  #disable stack unwinding on panic

[profile.release]
panic = "abort"  #disable stack unwinding on panic

